Commit Debian 3.0 (quilt) metadata
[dgit (9.13) quilt-fixup]

diff --git a/debian/patches/debian-changes b/debian/patches/debian-changes
--- a/debian/patches/debian-changes
+++ b/debian/patches/debian-changes
@@ -15,8 +15,18 @@ upload of upstream version 1.2.3, you could use:
 (If you have dgit, use `dgit clone openqa`, rather than plain `git clone`.)
 
 A single combined diff, containing all the changes, follows.
---- openqa-4.6.1639057582.07f0f29.orig/assets/stylesheets/openqa.scss
-+++ openqa-4.6.1639057582.07f0f29/assets/stylesheets/openqa.scss
+--- openqa-4.6.1640268275.25ac0d7.orig/assets/stylesheets/dashboard.scss
++++ openqa-4.6.1640268275.25ac0d7/assets/stylesheets/dashboard.scss
+@@ -24,6 +24,7 @@ td div.progress {
+         // don' use flex box because it leads to undesired overflow behavior
+         display: inline;
+         overflow: hidden;
++        padding-top: 10px;
+         a {
+             display: block;
+             width: 100%;
+--- openqa-4.6.1640268275.25ac0d7.orig/assets/stylesheets/openqa.scss
++++ openqa-4.6.1640268275.25ac0d7/assets/stylesheets/openqa.scss
 @@ -3,8 +3,11 @@
  @import "bootswatch_litera_theme.scss";
  @import "openqa_theme.scss";
@@ -31,8 +41,8 @@ A single combined diff, containing all the changes, follows.
  
  // include Bootstrap 4
  @import "../cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/bootstrap.scss";
---- openqa-4.6.1639057582.07f0f29.orig/assets/stylesheets/openqa_theme.scss
-+++ openqa-4.6.1639057582.07f0f29/assets/stylesheets/openqa_theme.scss
+--- openqa-4.6.1640268275.25ac0d7.orig/assets/stylesheets/openqa_theme.scss
++++ openqa-4.6.1640268275.25ac0d7/assets/stylesheets/openqa_theme.scss
 @@ -6,7 +6,6 @@ $grid-breakpoints: (
      xl: 1000px
  );
@@ -41,8 +51,8 @@ A single combined diff, containing all the changes, follows.
  $default-font:                "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
  $icon-font-path:              '/fonts/';
  $default-font-color:          #666666;
---- openqa-4.6.1639057582.07f0f29.orig/etc/apache2/vhosts.d/openqa-ssl.conf.template
-+++ openqa-4.6.1639057582.07f0f29/etc/apache2/vhosts.d/openqa-ssl.conf.template
+--- openqa-4.6.1640268275.25ac0d7.orig/etc/apache2/vhosts.d/openqa-ssl.conf.template
++++ openqa-4.6.1640268275.25ac0d7/etc/apache2/vhosts.d/openqa-ssl.conf.template
 @@ -1,12 +1,12 @@
  # sample apache config file for the ssl enabled openqa vhost.
  # At the very minimum you need to set the ServerName.
@@ -69,8 +79,8 @@ A single combined diff, containing all the changes, follows.
 -</IfDefine>
 -</IfDefine>
 -
---- openqa-4.6.1639057582.07f0f29.orig/etc/apache2/vhosts.d/openqa.conf.template
-+++ openqa-4.6.1639057582.07f0f29/etc/apache2/vhosts.d/openqa.conf.template
+--- openqa-4.6.1640268275.25ac0d7.orig/etc/apache2/vhosts.d/openqa.conf.template
++++ openqa-4.6.1640268275.25ac0d7/etc/apache2/vhosts.d/openqa.conf.template
 @@ -17,6 +17,7 @@
  # a2enmod proxy_http
  # a2enmod proxy_wstunnel
@@ -79,8 +89,8 @@ A single combined diff, containing all the changes, follows.
  
  <VirtualHost *:80>
  
---- openqa-4.6.1639057582.07f0f29.orig/etc/openqa/workers.ini
-+++ openqa-4.6.1639057582.07f0f29/etc/openqa/workers.ini
+--- openqa-4.6.1640268275.25ac0d7.orig/etc/openqa/workers.ini
++++ openqa-4.6.1640268275.25ac0d7/etc/openqa/workers.ini
 @@ -36,7 +36,7 @@
  # packages against the list of packages during the previous last good job.
  # Configuring this variable provides a command line to list the packages and
@@ -90,8 +100,8 @@ A single combined diff, containing all the changes, follows.
  
  # The section ids are the instance of the workers.
  # The key/value pairs will appear in vars.json
---- openqa-4.6.1639057582.07f0f29.orig/lib/OpenQA/CLI.pm
-+++ openqa-4.6.1639057582.07f0f29/lib/OpenQA/CLI.pm
+--- openqa-4.6.1640268275.25ac0d7.orig/lib/OpenQA/CLI.pm
++++ openqa-4.6.1640268275.25ac0d7/lib/OpenQA/CLI.pm
 @@ -32,8 +32,8 @@ openqa-cli - provides command-line acces
      # Show details for job from arbitrary host
      openqa-cli api --host http://openqa.example.com jobs/408
@@ -111,9 +121,9 @@ A single combined diff, containing all the changes, follows.
  
    Configuration:
      API key and secret are read from "client.conf" if not specified via CLI
---- openqa-4.6.1639057582.07f0f29.orig/lib/OpenQA/CLI/api.pm
-+++ openqa-4.6.1639057582.07f0f29/lib/OpenQA/CLI/api.pm
-@@ -73,8 +73,8 @@ sub command {
+--- openqa-4.6.1640268275.25ac0d7.orig/lib/OpenQA/CLI/api.pm
++++ openqa-4.6.1640268275.25ac0d7/lib/OpenQA/CLI/api.pm
+@@ -77,8 +77,8 @@ sub command {
      # Show details for job from arbitrary host
      openqa-cli api --host http://openqa.example.com jobs/408
  
@@ -124,7 +134,7 @@ A single combined diff, containing all the changes, follows.
  
      # List all jobs (CAUTION: this might time out for a large instance)
      openqa-cli api --host openqa.example.com jobs
-@@ -130,6 +130,7 @@ sub command {
+@@ -135,6 +135,7 @@ sub command {
      -j, --json                    Request content is JSON
          --osd                     Set target host to http://openqa.suse.de
          --o3                      Set target host to https://openqa.opensuse.org
@@ -132,8 +142,8 @@ A single combined diff, containing all the changes, follows.
          --param-file <param=file> Load content of params from files instead of
                                    from command line arguments. Multiple params
                                    may be specified by adding the option
---- openqa-4.6.1639057582.07f0f29.orig/lib/OpenQA/CLI/archive.pm
-+++ openqa-4.6.1639057582.07f0f29/lib/OpenQA/CLI/archive.pm
+--- openqa-4.6.1640268275.25ac0d7.orig/lib/OpenQA/CLI/archive.pm
++++ openqa-4.6.1640268275.25ac0d7/lib/OpenQA/CLI/archive.pm
 @@ -37,8 +37,8 @@ sub command {
  
    Usage: openqa-cli archive [OPTIONS] JOB PATH
@@ -153,8 +163,8 @@ A single combined diff, containing all the changes, follows.
      -t, --with-thumbnails          Download thumbnails as well
  
  =cut
---- openqa-4.6.1639057582.07f0f29.orig/lib/OpenQA/Command.pm
-+++ openqa-4.6.1639057582.07f0f29/lib/OpenQA/Command.pm
+--- openqa-4.6.1640268275.25ac0d7.orig/lib/OpenQA/Command.pm
++++ openqa-4.6.1640268275.25ac0d7/lib/OpenQA/Command.pm
 @@ -96,7 +96,8 @@ sub run {
        'apisecret=s' => sub { $self->apisecret($_[1]) },
        'host=s' => sub { $self->host($_[1] =~ m!^/|://! ? $_[1] : "https://$_[1]") },
@@ -165,8 +175,8 @@ A single combined diff, containing all the changes, follows.
  
      return $self->command(@args);
  }
---- openqa-4.6.1639057582.07f0f29.orig/lib/OpenQA/Utils.pm
-+++ openqa-4.6.1639057582.07f0f29/lib/OpenQA/Utils.pm
+--- openqa-4.6.1640268275.25ac0d7.orig/lib/OpenQA/Utils.pm
++++ openqa-4.6.1640268275.25ac0d7/lib/OpenQA/Utils.pm
 @@ -384,6 +384,8 @@ my %bugrefs = (
      kde => 'https://bugs.kde.org/show_bug.cgi?id=',
      fdo => 'https://bugs.freedesktop.org/show_bug.cgi?id=',
@@ -185,7 +195,7 @@ A single combined diff, containing all the changes, follows.
  
  my $MARKER_REFS = join('|', keys %bugrefs);
 --- /dev/null
-+++ openqa-4.6.1639057582.07f0f29/man/openqa-label-all.1.in
++++ openqa-4.6.1640268275.25ac0d7/man/openqa-label-all.1.in
 @@ -0,0 +1,72 @@
 +.\"                                      Hey, EMACS: -*- nroff -*-
 +.\" First parameter, NAME, should be all caps
@@ -259,11 +269,11 @@ A single combined diff, containing all the changes, follows.
 +.SH AUTHOR
 +This manual page was written by Philip Hands <phil@hands.com>, for the Debian
 +GNU/Linux system (but may be used by others).
---- openqa-4.6.1639057582.07f0f29.orig/profiles/apparmor.d/usr.share.openqa.script.openqa
-+++ openqa-4.6.1639057582.07f0f29/profiles/apparmor.d/usr.share.openqa.script.openqa
-@@ -83,6 +83,13 @@
-   /var/tmp/* rwk,
+--- openqa-4.6.1640268275.25ac0d7.orig/profiles/apparmor.d/usr.share.openqa.script.openqa
++++ openqa-4.6.1640268275.25ac0d7/profiles/apparmor.d/usr.share.openqa.script.openqa
+@@ -84,6 +84,13 @@
    owner /var/lib/openqa/share/tests/** rwl,
+   owner /var/lib/openqa/archive/** rwl,
  
 +  # Debian specific access to local assets
 +  /usr/share/fonts/*/fork-awesome/* r,
@@ -275,7 +285,7 @@ A single combined diff, containing all the changes, follows.
  
    profile /usr/bin/ssh {
      #include <abstractions/base>
-@@ -99,52 +106,6 @@
+@@ -100,53 +107,6 @@
  
    }
  
@@ -309,6 +319,7 @@ A single combined diff, containing all the changes, follows.
 -  /usr/bin/grep mrix,
 -  /usr/bin/head mrix,
 -  /usr/bin/hxselect mrix,
+-  /usr/bin/hxnormalize mrix,
 -  /usr/bin/jq rix,
 -  /usr/bin/mv ix,
 -  /usr/bin/mktemp rix,
@@ -328,8 +339,8 @@ A single combined diff, containing all the changes, follows.
    # Site-specific additions and overrides. See local/README for details.
    #include <local/usr.share.openqa.script.openqa>
  }
---- openqa-4.6.1639057582.07f0f29.orig/profiles/apparmor.d/usr.share.openqa.script.worker
-+++ openqa-4.6.1639057582.07f0f29/profiles/apparmor.d/usr.share.openqa.script.worker
+--- openqa-4.6.1640268275.25ac0d7.orig/profiles/apparmor.d/usr.share.openqa.script.worker
++++ openqa-4.6.1640268275.25ac0d7/profiles/apparmor.d/usr.share.openqa.script.worker
 @@ -27,8 +27,11 @@
    /dev/ptmx rw,
    /dev/pts/* rw,
@@ -390,8 +401,8 @@ A single combined diff, containing all the changes, follows.
    /var/lib/openqa/cache/ r,
    /var/lib/openqa/cache/** rwk,
    /var/lib/openqa/pool/ r,
---- openqa-4.6.1639057582.07f0f29.orig/script/fetchneedles
-+++ openqa-4.6.1639057582.07f0f29/script/fetchneedles
+--- openqa-4.6.1640268275.25ac0d7.orig/script/fetchneedles
++++ openqa-4.6.1640268275.25ac0d7/script/fetchneedles
 @@ -1,19 +1,19 @@
  #!/bin/sh -e
  : "${dbuser:="geekotest"}"
@@ -422,8 +433,8 @@ A single combined diff, containing all the changes, follows.
  
  : "${updateall:="0"}"
  : "${force:="0"}"
---- openqa-4.6.1639057582.07f0f29.orig/script/openqa-validate-yaml
-+++ openqa-4.6.1639057582.07f0f29/script/openqa-validate-yaml
+--- openqa-4.6.1640268275.25ac0d7.orig/script/openqa-validate-yaml
++++ openqa-4.6.1640268275.25ac0d7/script/openqa-validate-yaml
 @@ -19,6 +19,52 @@
  # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  # SOFTWARE.
@@ -477,8 +488,8 @@ A single combined diff, containing all the changes, follows.
  use strict;
  use warnings;
  use 5.010;
---- openqa-4.6.1639057582.07f0f29.orig/systemd/openqa-webui.service
-+++ openqa-4.6.1639057582.07f0f29/systemd/openqa-webui.service
+--- openqa-4.6.1640268275.25ac0d7.orig/systemd/openqa-webui.service
++++ openqa-4.6.1640268275.25ac0d7/systemd/openqa-webui.service
 @@ -4,6 +4,7 @@ Wants=apache2.service openqa-setup-db.se
  Before=apache2.service
  After=postgresql.service openqa-setup-db.service openqa-scheduler.service nss-lookup.target remote-fs.target
@@ -487,8 +498,8 @@ A single combined diff, containing all the changes, follows.
  
  [Service]
  User=geekotest
---- openqa-4.6.1639057582.07f0f29.orig/systemd/openqa-worker@.service
-+++ openqa-4.6.1639057582.07f0f29/systemd/openqa-worker@.service
+--- openqa-4.6.1640268275.25ac0d7.orig/systemd/openqa-worker@.service
++++ openqa-4.6.1640268275.25ac0d7/systemd/openqa-worker@.service
 @@ -7,6 +7,7 @@ Description=openQA Worker #%i
  Wants=network.target
  After=openqa-slirpvde.service network.target nss-lookup.target remote-fs.target
@@ -497,9 +508,9 @@ A single combined diff, containing all the changes, follows.
  
  [Service]
  Type=simple
---- openqa-4.6.1639057582.07f0f29.orig/t/43-cli-api.t
-+++ openqa-4.6.1639057582.07f0f29/t/43-cli-api.t
-@@ -92,6 +92,10 @@ subtest 'Host' => sub {
+--- openqa-4.6.1640268275.25ac0d7.orig/t/43-cli-api.t
++++ openqa-4.6.1640268275.25ac0d7/t/43-cli-api.t
+@@ -93,6 +93,10 @@ subtest 'Host' => sub {
      like $@, qr/Usage: openqa-cli api/, 'usage';
      is $api->host, 'https://openqa.opensuse.org', 'host';
  
@@ -510,8 +521,8 @@ A single combined diff, containing all the changes, follows.
      eval { $api->run(@host) };
      like $@, qr/Usage: openqa-cli api/, 'usage';
      is $api->host, $host, 'host';
---- openqa-4.6.1639057582.07f0f29.orig/t/43-cli-archive.t
-+++ openqa-4.6.1639057582.07f0f29/t/43-cli-archive.t
+--- openqa-4.6.1640268275.25ac0d7.orig/t/43-cli-archive.t
++++ openqa-4.6.1640268275.25ac0d7/t/43-cli-archive.t
 @@ -77,6 +77,10 @@ subtest 'Host' => sub {
      like $@, qr/Usage: openqa-cli archive/, 'usage';
      is $archive->host, 'https://openqa.opensuse.org', 'host';
@@ -523,8 +534,8 @@ A single combined diff, containing all the changes, follows.
      eval { $archive->run(@host) };
      like $@, qr/Usage: openqa-cli archive/, 'usage';
      is $archive->host, $host, 'host';
---- openqa-4.6.1639057582.07f0f29.orig/templates/webapi/comments/add_comment_form_groups.html.ep
-+++ openqa-4.6.1639057582.07f0f29/templates/webapi/comments/add_comment_form_groups.html.ep
+--- openqa-4.6.1640268275.25ac0d7.orig/templates/webapi/comments/add_comment_form_groups.html.ep
++++ openqa-4.6.1640268275.25ac0d7/templates/webapi/comments/add_comment_form_groups.html.ep
 @@ -19,7 +19,7 @@
                  </p>
                  <ul>
@@ -534,3 +545,30 @@ A single combined diff, containing all the changes, follows.
                      </li>
                      <li>
                          For generic labels use <code>label:<i>keyword</i></code> where <i>keyword</i> can be any valid character up to the next whitespace, e.g. "false_positive".
+--- openqa-4.6.1640268275.25ac0d7.orig/tools/generate-packed-assets
++++ openqa-4.6.1640268275.25ac0d7/tools/generate-packed-assets
+@@ -35,6 +35,8 @@ ASSETPACK_PLUGINS=$(grep 'AssetPack' lib
+ BUILD_CACHE="plugin AssetPack => { pipes => [qw(${ASSETPACK_PLUGINS})]} and app->asset->process()"
+ BUILD_CACHE_OPTS='-Ilib/ -MMojolicious::Lite'
+ 
++MISSING=0
++
+ generate() {
+     # shellcheck disable=SC2039
+     for _ in {1..3}; do
+@@ -42,8 +44,15 @@ generate() {
+         env MOJO_MODE="$1" perl $BUILD_CACHE_OPTS -e "$BUILD_CACHE" > /dev/null && return 0
+         sleep 1
+     done
++    MISSING=1
+ }
+ 
+ # Possibly requires a retry in case of CDN failures
+ generate "test"
+ generate "development"
++
++if [ "$GENERATE_PACKED_ASSETS_FAILS_ON_MISSING_ASSETS" ]; then
++    # for Debian packaging, fail at this point if any assets are missing
++    exit $MISSING
++fi
++exit 0
